repos:
  - repo: local
    hooks:
      - id: deno-fmt
        name: Deno Format
        entry: deno fmt
        language: system
        types: [file]
        files: \.(js|ts|jsx|tsx)$
        pass_filenames: true
